carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
]

django_eccomerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django_eccomerce import views

urlpatterns = [
    path('not_admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
]

carts/models.py
from django.db import models

from accounts.models import Account
from store.models import Product, Variation


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return str(self.product)

store/models.py
from django.db import models
from django.db.models import Avg, Count
from django.urls import reverse

from accounts.models import Account
from category.models import Category


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    def average_rating(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = round(float(reviews['average']) * 2) / 2  # round to the nearest .5; e.g 4.3 -> 4.5, 4.2 -> 4.0

        return avg

    def reviews_count(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count


VARIATION_CATEGORY_CHOISE = (
    ('color', 'color'),
    ('size', 'size')
)


class VariationManager(models.Manager):
    def color(self):
        return self.filter(variation_category='color', is_active=True)

    def size(self):
        return self.filter(variation_category='size', is_active=True)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=VARIATION_CATEGORY_CHOISE)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):

    class Meta:
        verbose_name = 'product_gallery'
        verbose_name_plural = 'product gallery'

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products/', max_length=255)

    def __str__(self):
        return self.product.product_name

store/forms.py
from django import forms

from store.models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from carts.models import Cart, CartItem
from store.models import Product, Variation


def _cart_id(request):
    session = request.session.session_key
    if not session:
        session = request.session.create()

    return session


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    product_variations = []
    if current_user.is_authenticated:
        if request.method == 'POST':
            for variation_category, variation_value in request.POST.items():
                try:
                    variation = Variation.objects.get(product=product,
                                                      variation_category__iexact=variation_category,
                                                      variation_value__iexact=variation_value)
                    product_variations.append(variation)
                except ObjectDoesNotExist:
                    pass

        is_cart_item_exist = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exist:
            cart_items = CartItem.objects.filter(product=product, user=current_user)

            existing_variations = []
            ids = []
            for item in cart_items:
                existing_variation = item.variations.all()
                existing_variations.append(list(existing_variation))
                ids.append(item.id)

            if product_variations in existing_variations:
                index = existing_variations.index(product_variations)
                item_id = ids[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variations) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variations)
                # cart_item.quantity += 1
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user
            )
            if len(product_variations) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variations)
            cart_item.save()
    else:
        if request.method == 'POST':
            for variation_category, variation_value in request.POST.items():
                try:
                    variation = Variation.objects.get(product=product,
                                                      variation_category__iexact=variation_category,
                                                      variation_value__iexact=variation_value)
                    product_variations.append(variation)
                except ObjectDoesNotExist:
                    pass

        try:
            cart_obj = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart_obj = Cart.objects.create(
                cart_id=_cart_id(request)
            )
            cart_obj.save()

        is_cart_item_exist = CartItem.objects.filter(product=product, cart=cart_obj).exists()
        if is_cart_item_exist:
            cart_items = CartItem.objects.filter(product=product, cart=cart_obj)

            existing_variations = []
            ids = []
            for item in cart_items:
                existing_variation = item.variations.all()
                existing_variations.append(list(existing_variation))
                ids.append(item.id)

            if product_variations in existing_variations:
                index = existing_variations.index(product_variations)
                item_id = ids[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart_obj)
                if len(product_variations) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variations)
                # cart_item.quantity += 1
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart_obj
            )
            if len(product_variations) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variations)
            cart_item.save()

    return redirect('cart')


def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    current_user = request.user
    try:
        if current_user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=current_user, id=cart_item_id)
        else:
            cart_obj = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart_obj, id=cart_item_id)

        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass

    return redirect('cart')


def remove_cart_item(request, product_id, cart_item_id):
    current_user = request.user
    product = get_object_or_404(Product, id=product_id)

    if current_user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=current_user, id=cart_item_id)
    else:
        cart_obj = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart_obj, id=cart_item_id)

    cart_item.delete()

    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    tax = None
    grand_total = None

    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart_obj = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart_obj, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (2 * total) / 100
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)


@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    tax = None
    grand_total = None

    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart_obj = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart_obj, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (2 * total) / 100
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/checkout.html', context)

store/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator

from category.models import Category
from orders.models import OrderProduct
from store.forms import ReviewForm
from store.models import Product, ReviewRating, ProductGallery

PRODUCTS_COUNT_ON_STORE_PAGE = 3


def store(request, category_slug=None):
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.all().filter(category=category).order_by('id')
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')

    paginator = Paginator(products, PRODUCTS_COUNT_ON_STORE_PAGE)
    page = request.GET.get('page')
    paged_products = paginator.get_page(page)
    products_count = products.count()

    context = {
        'products': paged_products,
        'products_count': products_count,
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    single_product = Product.objects.get(slug=product_slug, category__slug=category_slug)

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    # get reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)

    # get product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        'single_product': single_product,
        'orderproduct': orderproduct,
        'reviews': reviews,
        'product_gallery': product_gallery,
    }
    return render(request, 'store/product_detail.html', context)


def search(request):
    products = None
    products_count = 0
    keyword = request.GET.get('keyword')
    if keyword:
        products = Product.objects.filter(product_name__icontains=keyword)
        products_count = products.count()

    context = {
        "products": products,
        'products_count': products_count,
    }
    return render(request, 'store/store.html', context)


@login_required
def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == "POST":
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated')

        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            print(form)
            print(form.cleaned_data['rating'])
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()

                messages.success(request, 'Thank you! Your review has been submitted')

        return redirect(url)

templates/store/cart.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
    <div class="text-center">
        <h2>Cart is empty</h2>
        <br>
        <a href="{% url 'store' %}" class="btn btn-primary"> Continue shopping </a>
    </div>
{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for cart_item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><a href="{{ cart_item.product.get_url }}"><img src="{{ cart_item.product.images.url }}" class="img-sm"></a></div>
			<figcaption class="info">
				<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
				<p class="text-muted small">
                    {% for variation in cart_item.variations.all %}
                        {{  variation.variation_category | capfirst }}: {{ variation.variation_value }} <br>
                    {% endfor %}
                </p>
			</figcaption>
		</figure>
	</td>
	<td>
		<!-- col.// -->
        <div class="col">
            <div class="input-group input-spinner">
                <div class="input-group-prepend">
                    <a href="{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                </div>
                <input type="text" class="form-control"  value="{{ cart_item.quantity }}">
                <div class="input-group-append">
                    <form action="{% url 'add_cart' cart_item.product.id %}" method="POST">
                        {% csrf_token %}
                        {% for item in cart_item.variations.all %}
                            <input type="hidden" name="{{ item.variation_category }}" value="{{ item.variation_value }}">
                        {% endfor %}
                        <button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
                    </form>
                </div>
            </div> <!-- input-group.// -->
        </div>
        <!-- col.// -->
	</td>
	<td>
		<div class="price-wrap">
			<var class="price">${{ cart_item.sub_total }}</var>
			<small class="text-muted"> ${{ cart_item.product.price }} </small>
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right">
	<a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure?')" class="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{ total }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{ tax }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Grand Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap mainImage">
	   <center><img src="{{ single_product.images.url }}"></center>
	</div> <!-- img-big-wrap.// -->

</article> <!-- gallery-wrap .end// -->
    <ul class="thumb">
        <li>
            <a href="{{ single_product.images.url }}" target="mainImage"><img src="{{ single_product.images.url }}" alt="Product Image"></a>
            {% for image in product_gallery %}
            <a href="{{ image.image.url}}" target="mainImage"><img src="{{ image.image.url}}" alt="Product Image"></a>
            {% endfor %}
        </li>
    </ul>
		</aside>
		<main class="col-md-6 border-left">
            <form action="{% url 'add_cart' single_product.id %}" method="POST">
            {% csrf_token %}
                <article class="content-body">
                <h2 class="title">{{ single_product.product_name }}</h2>
                <div class="rating-star">
                    <span>
                        <i class="fa fa-star{% if single_product.average_rating == 0.5 %}-half-o{% elif review.average_rating < 1.0 %}-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.average_rating == 1.5 %}-half-o{% elif review.average_rating < 2.0 %}-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.average_rating == 2.5 %}-half-o{% elif review.average_rating < 3.0 %}-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.average_rating == 3.5 %}-half-o{% elif review.average_rating < 4.0 %}-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.average_rating == 4.5 %}-half-o{% elif review.average_rating < 5.0 %}-o {% endif %}" aria-hidden="true"></i>
                    </span>
                </div>
                <p>Reviews: {{ single_product.reviews_count }}</p>
                <div class="mb-3">
                    <var class="price h4">$ {{ single_product.price }}</var>
                </div>

                <p>{{ single_product.description }}</p>
                <hr>
                    <div class="row">
                        <div class="item-option-select">
                            <h6>Choose Color</h6>
                            <select name="color" class="form-control">
                                {% for item in single_product.variation_set.color %}
                                    <option value="{{ item.variation_value | lower }}">{{ item.variation_value | capfirst }}</option>
                                {% endfor %} }
                            </select>
                        </div>
                    </div> <!-- row.// -->
                    <div class="row">
                        <div class="item-option-select">
                            <h6>Select Size</h6>
                            <select name="size" class="form-control">
                                {% for item in single_product.variation_set.size %}
                                    <option value="{{ item.variation_value | lower }}">{{ item.variation_value | capfirst }}</option>
                                {% endfor %} }
                            </select>
                        </div>
                    </div> <!-- row.// -->
                    <hr>
                    {% if single_product.stock <= 0 %}
                        <h5 class="text-danger">Out of stock</h5>
                    {% else %}
                        <button type=submit class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
                    {% endif %}
                </article> <!-- product-info-aside .// -->
            </form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
	<div class="col-md-9">
        <header>
            <form action="{% url 'submit_review' single_product.id %}" method="POST">
                {% csrf_token %}
                <div>
                    <!-- Rating stars -->
                    <label>How do your rate this product?</label>
                    <br>
                    <div class="rate">
                        <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
                        <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
                        <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
                        <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
                        <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
                        <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
                        <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
                        <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
                        <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
                        <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
                    </div>
                    <br>

                    Review title:
                    <input type="text" class="form-control" name="subject">
                    <br>
                    Review:
                    <textarea name="review" rows="5" class="form-control"></textarea>
                    <br>
                    {% if user.is_authenticated %}
                        {% if orderproduct %}
                            <input type="submit" class="btn btn-primary" value="Submit">
                        {% else %}
                            <p>You must purchase this product to left a review.</p>
                        {% endif %}
                    {% else %}
                        <p>You must be logged in. <span><a href="{% url 'login' %}">Log in</a></span></p>
                    {% endif %}
                </div>
                <br>
                {% include 'alerts.html' %}
            </form>
        </header>
    {% if reviews %}
        <header class="section-heading">
            <h3>Customer Reviews </h3>
            <div class="rating-star">
                <span>
                    <i class="fa fa-star{% if single_product.average_rating == 0.5 %}-half-o{% elif review.average_rating < 1.0 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.average_rating == 1.5 %}-half-o{% elif review.average_rating < 2.0 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.average_rating == 2.5 %}-half-o{% elif review.average_rating < 3.0 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.average_rating == 3.5 %}-half-o{% elif review.average_rating < 4.0 %}-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.average_rating == 4.5 %}-half-o{% elif review.average_rating < 5.0 %}-o {% endif %}" aria-hidden="true"></i>
                </span>
            </div>
            <p>Reviews: {{ single_product.reviews_count }}</p>
        </header>
        {% for review in reviews %}
        <article class="box mb-3">
            <div class="icontext w-100">
                <div class="text">
                    <span class="date text-muted float-md-right"> {{ review.updated_at }}</span>
                    <h6 class="mb-1">{{ review.user.first_name }} {{ review.user.last_name }}</h6>
                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1.0 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2.0 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3.0 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4.0 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5.0 %}-o {% endif %}" aria-hidden="true"></i>
                        </span>
                    </div>
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <h6>{{ review.subject }}</h6>
                <p>
                    {{ review.review }}
                </p>
            </div>
        </article>
        {% endfor %}
    {% else %}
        <h4>There is no customer review. You can be first!</h4>
    {% endif %}



	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}